services:
  bot:
    image: "dating_bot"
    container_name: bot
    restart: on-failure
    build:
      context: .
      dockerfile: ./bot.Dockerfile
    command: poetry run python -m src.dating_backend.main.bot
    env_file:
      - ".env"

  db:
    container_name: "dating_db"
    image: postgres:16-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test:
        [
          "CMD-SHELL", "pg_isready -d dating_database -U $${POSTGRES_USER}"
        ]
      interval: 2s
      timeout: 60s
      retries: 10
      start_period: 3s

volumes:
  pg_data:
